# Generated by Django 5.1.6 on 2025-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator')], default='student', max_length=10, verbose_name='User Type'),
        ),
    ]
